### ISSUE TITLE
Don't exclude holidays 

### ISSUE THREAD

**Issue by Mopade** [janzzon/difftimeOffice#3]
Hello, 

Sorry for my question, it is not an issue, but : I would like to use your function but I don't want to exclude holidays. Just non-opening hours and weekends. 

Is it possible ? 

Thank you,

**Comment by johncassil** [comment]
You should not have to include anything for holidays.  The default is to exclude the dates ('01/01/1901', '01/02/1901'), but if that's a problem, you can set it to holidays = '01/01/1001' or something similar.

**Comment by Mopade** [comment]
Hello, 
Thank you for your answer but I'm not sure to understand (sorry) :-) 
If I do : 
"difftime_office_hours(started, ended, working_hours = c(8, 16))" 
Are by default some holidays excluded ? 
If yes : where can I find which holidays are excluded ? 
Because as I am French, the holidays are not the same so I don't want by default to exclude perhaps some days which are working days in France. 
Thank you

**Comment by johncassil** [comment]
The way this function was created, you have to do the work to determine the actual dates of the holidays you want to exclude and feed the list of dates in. By default, the only "holiday" it excludes is in 1901, so practically, if you use it without a holidays argument, it's not going to exclude any holidays.

If you want it to exclude French holidays, you need to determine the actual dates of the holidays and feed them to the holidays argument. For example, googling tells me that a French holiday in 2019 is Armistice Day on Mon, Nov 11, 2019, and another one is Christmas on Wed, Dec 25, 2019.

If you wanted to exclude these holidays in 2019, while using this function, you would add this argument: 

holidays = c('11/11/2019', '12/25/2019')

You will need to add an additional date for each holiday during the time window of your analysis. 

Apologies that the date needs to be a string in month day year format... I know it's a very American/Excel way of writing dates.

Does this answer your question?

**Comment by johncassil** [comment]
One more note, it's designed this way (to require a list of holidays) for a reason. Holidays vary not only by country, but by workplace, so I wanted to allow the user the flexibility to specify which dates were and were not holidays.

**Comment by Mopade** [comment]
Wow it's perfect! 
I understand how it works now. Thank you very much for your help John! :-)
